config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :users

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :timeoutable
  validates :first_name, presence: true, length: { minimum: 1 }
  # validates: last_name, presence: true, length: { minimum: 1 }
  validates :password, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
    @user = User.new(user_params)

    @user.save
    redirect_to @user
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :confirm_password)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monstagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Destroy All Monsters</h1>

<table>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %> <%= user.last_name %></td>
      <td><%= link_to 'Profile', user_path(user) %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
  <body>
    <h1><br>Enter your details ... if you dare ...</h1>
    <br>
    <%= form_with scope: :user, url: users_path, local: true do |form| %>
      <p>
        <%= form.label :first_name %><br>
        <%= form.text_field :first_name %>
      </p>

      <p>
        <%= form.label :last_name %><br>
        <%= form.text_field :last_name %>
      </p>

      <p>
        <%= form.label :email %><br>
        <%= form.text_field :email %>
      </p>

      <p>
        <%= form.label :password %><br>
        <%= form.text_field :password %>
      </p>

      <p>
        <%= form.label :confirm_password %><br>
        <%= form.text_field :confirm_password %>
      </p>

      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </body>
</html>

app/views/users/show.html.erb
<p>
  <h1>Welcome, <%= @user.last_name == (nil || "") ? @user.first_name : @user.first_name + " " + @user.last_name %>.</h1>
  <br><h2>You will never leave.</h2>
</p>
<%= link_to 'See All Users', users_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>MONSTAGRAM!!!</title>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>
    <style>
      @font-face { font-family: Fiddums; src: url('Fiddums.ttf'); }
      h1 {
        font-family: Fiddums
      }
      </style>
  </head>
  <body>
    <h1><br>Welcome to Monstagram ...</h1>
    <br>
    <%= link_to 'Register', new_user_path %>
  </body>
</html>